app_name: psc-verification-api
group: api
weight: 900
routes:
  1: ^/persons-with-significant-control-verification
  2: ^/transactions/.*/persons-with-significant-control-verification
  3: ^/private/transactions/.*/persons-with-significant-control
